[package]
name = "r0z-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4.13"

[dependencies.r0z]
path = "../crates/r0z"

[workspace]
members = ["."]

[[bin]]
name = "fuzz_has"
path = "fuzz_targets/fuzz_has.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_message_gets"
path = "fuzz_targets/fuzz_message_gets.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_message_alloc"
path = "fuzz_targets/fuzz_message_alloc.rs"
test = false
doc = false
bench = false
