[package]
name = "r0z-sys"
version.workspace = true
authors = [
    "a.rottmann@gmx.at",
    "erick.tryzelaar@gmail.com",
]
build = "build/main.rs"
categories = ["external-ffi-bindings"]
edition = "2015"
keywords = ["zeromq", "zmq", "ffi", "bindings"]
license.workspace = true
links = "zmq"
readme = "../../README.md"
repository.workspace = true
description = "Native ZeroMQ (libzmq) build and FFI bindings"

[package.metadata.docs.rs]
targets = []

[features]
libsodium = ["libsodium-sys-stable"]

[dependencies]
libc.workspace = true
libsodium-sys-stable = { workspace = true, optional = true }

[build-dependencies]
zeromq-src.workspace = true
