on: [push, pull_request]

name: Continuous integration

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            packages: --workspace
          - os: macos-latest
            packages: --workspace
          - os: windows-latest
            packages: --workspace --exclude r0rz-async
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Cargo build
        run: cargo build ${{ matrix.packages }} --all-targets
  test:
    name: Test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            packages: --workspace
          - os: macos-latest
            packages: --workspace
          - os: windows-latest
            packages: --workspace --exclude r0rz-async
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Cargo test
        run: cargo test ${{ matrix.packages }} --all-targets
      - name: Cargo doc tests
        run: cargo test ${{ matrix.packages }} --doc
  lint:
    name: Lint
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            packages: --workspace
          - os: macos-latest
            packages: --workspace
          - os: windows-latest
            packages: --workspace --exclude r0rz-async
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Cargo clippy
        run: cargo clippy ${{ matrix.packages }} --all-targets -- -D warnings
